### ISSUE TITLE
Player can see everything in the map (no fog of war)

### ISSUE THREAD

**Issue by Lowdive** [spring1944/Scenario-Editor-S44#3]
I believe it started happening in spring engine 100, whenever I start an editor session or whenever I play an editor mission, I can see everything in the map, my LoS is unlimited, I can see enemy units all the time anywhere on the map.

I have tried using the perspective picker, for: spectator, team1, team0, team 2... nothing works.

**Comment by kanatohodets** [comment]
Hi Lowdive -- I started looking at this (the "global LoS executor" message at editor load is a big hint :)), but my more immediate question is: are you able to create any kind of playable scenario? I tested a few really simple things (just deleting the starting units and adding a few to each side), but no matter how I launched the exported scenario.sdz, the game was launched in the scenario editor, not as a playable thing. 

I suspect part of the problem is that when you load the game, you're loading it in editing conditions, which naturally have global LoS. If we figure out how to actually play the scenario and there's still global LoS, I can dig a little deeper.

**Comment by Lowdive** [comment]
Oh yeah it's just you need to export, not save, when you export you get a playable .sdz "map/mod" and editor stuff won't show up, but LoS is still an issue there.

Ok I re-read that, and figured you followed the same procedure I described, so I checked and also got an editor mode launch... I could swear I had managed to get a game without scenario editor...
It comes to mind I played with the script.txt that generates in the save, but I don't recall exactly how I made it work. I'll check tomorrow, right now I'm loaded.

**Comment by kanatohodets** [comment]
ah ha, thanks for the tip -- indeed, the export has both script-dev.txt and script.txt. Running `spring script.txt` launches it in 'play' mode. Now I can investigate the LoS issue. At first glance, my bet is that you're actually a spectator (that's how my export turned out).

**Comment by kanatohodets** [comment]
Ok, some progress:

first, my game export had me in spectator mode. I hacked script.txt to remove an AI and 'spectator=1' from the player def; now I could play.

next, global LoS: it looks like the scened widget was doing this as a temporary hack. I've pushed a commit to s44-scened that disables this.

finally: there's still a lot of funky stuff going on. units don't shoot (???); deployment doesn't work, probably more. will dig more.

**Comment by Lowdive** [comment]
Ahh hence my other issue, units wont shoot at each other on saved scenario, I remember now...

**Comment by kanatohodets** [comment]
@Lowdive with this and the other commit to fix firing, I think you're mostly unblocked -- is that true?

**Comment by Lowdive** [comment]
pretty much, yes, I think too!

**Comment by kanatohodets** [comment]
Great!

Let me know if you run into any more really awkward scenario editor bits -- I want to keep you churning out missions as much as possible :D
